### ISSUE TITLE
networkreader : erros

### ISSUE THREAD

**Issue by dsmello** [AlexProgramm/pybrain3#2]
Hi, had some problems on network reader.

1. File : networkreader.py    Line: 40  
IS : `        import pybrain.structure.networks.custom #@Reimport @UnusedImport
`
Change to : `        # import pybrain.structure.networks.custom #@Reimport @UnusedImport
`

2. File : networkreader.py    Line: 115
IS : `            params = eval(string.strip(pnode.firstChild.data))
`
Change to : `            params = eval(str.strip(pnode.firstChild.data))
`

**Comment by dsmello** [comment]
i'm made a pull request with the fix

**Comment by AlexProgramm** [comment]
Thank you for fixing. I'm sorry for abandoning this repository.
